// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7iuSa1MtYgfxVkY23CKsNe
// Component: IiU0zwRMTX
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: yqtmlg7NYqV/component

import { useScreenVariants as useScreenVariants_22Zb8UtchRz3S } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 22ZB8UtchRz3s/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_frontend.module.css"; // plasmic-import: 7iuSa1MtYgfxVkY23CKsNe/projectcss
import sty from "./PlasmicNewPage.module.css"; // plasmic-import: IiU0zwRMTX/css

import Logosvg2Icon from "./icons/PlasmicIcon__Logosvg2"; // plasmic-import: nYpSZLj3pX/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: lA3ZF7ASXV-/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: BrTSIF8bz_5/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: MQpoDb7OWAs/icon

export type PlasmicNewPage__VariantMembers = {};

export type PlasmicNewPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewPage__VariantsArgs;
export const PlasmicNewPage__VariantProps = new Array<VariantPropType>();

export type PlasmicNewPage__ArgsType = {};
type ArgPropType = keyof PlasmicNewPage__ArgsType;
export const PlasmicNewPage__ArgProps = new Array<ArgPropType>();

export type PlasmicNewPage__OverridesType = {
  root?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  features?: p.Flex<"section">;
  container4?: p.Flex<"div">;
  outerRow2?: p.Flex<"div">;
  row2?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  outerRow3?: p.Flex<"div">;
  row4?: p.Flex<"div">;
  container6?: p.Flex<"div">;
  outerRow4?: p.Flex<"div">;
  row3?: p.Flex<"div">;
  testimonials?: p.Flex<"section">;
  outer?: p.Flex<"div">;
  footerTop?: p.Flex<"div">;
  footerBottom?: p.Flex<"div">;
  container2?: p.Flex<"div">;
};

export interface DefaultNewPageProps {}

export const defaultNewPage__Args: Partial<PlasmicNewPage__ArgsType> = {};

function PlasmicNewPage__RenderFunc(props: {
  variants: PlasmicNewPage__VariantsArgs;
  args: PlasmicNewPage__ArgsType;
  overrides: PlasmicNewPage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultNewPage__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_22Zb8UtchRz3S()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              sty.root
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__yng07)}>
              <div className={classNames(projectcss.all, sty.freeBox__dl925)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__a9AZx)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__yjoE)}
                  >
                    {true ? (
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__qL94O
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Logosvg2Icon
                          className={classNames(projectcss.all, sty.svg__cHw68)}
                          role={"img"}
                        />
                      </p.PlasmicLink>
                    ) : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__rnQtg)}
                    >
                      <p.Stack
                        as={p.PlasmicLink}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__nYtnR
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mpPaq
                            )}
                            role={"img"}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__scAsq
                          )}
                        >
                          {"About Us"}
                        </div>

                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__glRf5
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </p.Stack>

                      <p.Stack
                        as={p.PlasmicLink}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__q4JNh
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cs4P
                            )}
                            role={"img"}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tySxt
                          )}
                        >
                          {"Features"}
                        </div>

                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nC6Au
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </p.Stack>

                      <p.Stack
                        as={p.PlasmicLink}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__u9HWf
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aMha4
                            )}
                            role={"img"}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7NJrZ
                          )}
                        >
                          {"Pricing "}
                        </div>

                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__s0JFp
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </p.Stack>

                      <p.Stack
                        as={p.PlasmicLink}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__bP3QV
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__y87Hb
                            )}
                            role={"img"}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__taSc
                          )}
                        >
                          {"Contact"}
                        </div>

                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__b1S3C
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </p.Stack>

                      <p.Stack
                        as={p.PlasmicLink}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__crS8P
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__btoOo
                            )}
                            role={"img"}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__et3GR
                          )}
                        >
                          {"Blog"}
                        </div>

                        {false ? (
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___1X2H8
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </p.Stack>

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___32ZD1
                        )}
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ng4Oy
                          )}
                        >
                          {"Get started"}
                        </div>
                      </Button>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <div className={classNames(projectcss.all, sty.freeBox__yoRzX)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__g4MGs)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5QgqS
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kteo4
                        )}
                      >
                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Ready to accept or acquiesce willing."
                            : "Hero for your SaaS landing page."}
                        </h1>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ipCxF
                          )}
                        >
                          {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ."
                          }
                        </div>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button___4OT
                          )}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___3OZki
                              )}
                              role={"img"}
                            />
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__db5Cl
                            )}
                          >
                            {"Get started"}
                          </div>
                        </Button>
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jVn4Z)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3PmaP
                        )}
                      />
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>

            {true ? (
              <section
                data-plasmic-name={"features"}
                data-plasmic-override={overrides.features}
                className={classNames(projectcss.all, sty.features)}
              >
                <div className={classNames(projectcss.all, sty.column__jb5S5)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__zjwVe
                    )}
                  >
                    {"Value propositions headline."}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l6Xpb
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                    }
                  </div>

                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <div
                      data-plasmic-name={"outerRow2"}
                      data-plasmic-override={overrides.outerRow2}
                      className={classNames(projectcss.all, sty.outerRow2)}
                    >
                      <div
                        data-plasmic-name={"row2"}
                        data-plasmic-override={overrides.row2}
                        className={classNames(projectcss.all, sty.row2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__gmp8S
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___2846R
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__h2RxX
                                )}
                              />

                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__gtvAs
                                )}
                              >
                                {"Some value proposition of your service."}
                              </h3>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__fmQKc
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                }
                              </div>

                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__vrY5U
                                )}
                                color={"blue" as const}
                                endIcon={
                                  <ArrowRightsvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___3Akpz
                                    )}
                                    role={"img"}
                                  />
                                }
                                shape={"rounded" as const}
                                showEndIcon={true}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__wMWp0
                                  )}
                                >
                                  {"Learn more"}
                                </div>
                              </Button>
                            </p.Stack>
                          ) : null}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__l2Ocr
                          )}
                        >
                          {true ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__xXtud
                              )}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__l9PdU)}
                                displayHeight={"400px" as const}
                                displayMaxHeight={"none" as const}
                                displayMaxWidth={"none" as const}
                                displayMinHeight={"0" as const}
                                displayMinWidth={"0" as const}
                                displayWidth={"400px" as const}
                                loading={"lazy" as const}
                                src={{
                                  src: "/plasmic/frontend/images/image2.jpeg",
                                  fullWidth: 1920,
                                  fullHeight: 1280,
                                  aspectRatio: undefined
                                }}
                              />
                            </div>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"container5"}
                    data-plasmic-override={overrides.container5}
                    className={classNames(projectcss.all, sty.container5)}
                  >
                    <div
                      data-plasmic-name={"outerRow3"}
                      data-plasmic-override={overrides.outerRow3}
                      className={classNames(projectcss.all, sty.outerRow3)}
                    >
                      <div
                        data-plasmic-name={"row4"}
                        data-plasmic-override={overrides.row4}
                        className={classNames(projectcss.all, sty.row4)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__zHhQb
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__ynr5T)}
                            displayHeight={"400px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"none" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"400px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image3.jpeg",
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__ljCnQ
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__hzXkl
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__lxxQ
                                )}
                              />

                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__h3RI7
                                )}
                              >
                                {"Some value proposition of your service."}
                              </h3>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__uCy1U
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                }
                              </div>

                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__pUwEo
                                )}
                                color={"blue" as const}
                                endIcon={
                                  <ArrowRightsvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__eflff
                                    )}
                                    role={"img"}
                                  />
                                }
                                shape={"rounded" as const}
                                showEndIcon={true}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__lPzk0
                                  )}
                                >
                                  {"Learn more"}
                                </div>
                              </Button>
                            </p.Stack>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"container6"}
                    data-plasmic-override={overrides.container6}
                    className={classNames(projectcss.all, sty.container6)}
                  >
                    <div
                      data-plasmic-name={"outerRow4"}
                      data-plasmic-override={overrides.outerRow4}
                      className={classNames(projectcss.all, sty.outerRow4)}
                    >
                      <div
                        data-plasmic-name={"row3"}
                        data-plasmic-override={overrides.row3}
                        className={classNames(projectcss.all, sty.row3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___1N3Zn
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__wuHLr
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__zqiAv
                                )}
                              />

                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3___2O16U
                                )}
                              >
                                {"Some value proposition of your service."}
                              </h3>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___06BP5
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                }
                              </div>

                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__cGfhV
                                )}
                                color={"blue" as const}
                                endIcon={
                                  <ArrowRightsvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__aoDsa
                                    )}
                                    role={"img"}
                                  />
                                }
                                shape={"rounded" as const}
                                showEndIcon={true}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__o1MSc
                                  )}
                                >
                                  {"Learn more"}
                                </div>
                              </Button>
                            </p.Stack>
                          ) : null}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__cib5D
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__gGsi)}
                            displayHeight={"400px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"none" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"400px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image4.jpeg",
                              fullWidth: 640,
                              fullHeight: 360,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            ) : null}

            <section
              data-plasmic-name={"testimonials"}
              data-plasmic-override={overrides.testimonials}
              className={classNames(projectcss.all, sty.testimonials)}
            >
              <div className={classNames(projectcss.all, sty.column__f81Oe)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__hdn9O
                  )}
                >
                  {"Testimonials"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qvghW
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                  }
                </div>

                <div
                  className={classNames(projectcss.all, sty.columns___2MrMl)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__bvV5T)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__mOAc2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__vZtWr
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2___7N7LL
                          )}
                        >
                          {"“"}
                        </h2>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4MpV
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns___3Da5B
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column___8PEyn
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__rQlFr)}
                              displayHeight={"auto" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"auto" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/frontend/images/image5.jpeg",
                                fullWidth: 160,
                                fullHeight: 160,
                                aspectRatio: undefined
                              }}
                            />
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__eL8Ln
                            )}
                          >
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5___52Fb
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h5>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__pejCx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___7STvh
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__svf6J
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__y1Jcd)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/frontend/images/image6.png",
                            fullWidth: 140,
                            fullHeight: 140,
                            aspectRatio: undefined
                          }}
                        />

                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___4I8Pn
                          )}
                        >
                          {"Zulia Maron Duo"}
                        </h5>

                        <div
                          before={"" as const}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__adC5B
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__txOc1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__rpfIf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nFzRn
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__fKqL9
                          )}
                        >
                          {"“"}
                        </h2>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h0Lw
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns___1Quqo
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__iEsz1
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__pi5S7)}
                              displayHeight={"auto" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"auto" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/frontend/images/image7.jpeg",
                                fullWidth: 160,
                                fullHeight: 160,
                                aspectRatio: undefined
                              }}
                            />
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__fM2Kr
                            )}
                          >
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__uVyO9
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h5>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            <section className={classNames(projectcss.all, sty.columns__i152N)}>
              <div className={classNames(projectcss.all, sty.column__z6Tro)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__mb35G
                  )}
                >
                  {"Blog"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ryKtq
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                  }
                </div>

                <div
                  className={classNames(projectcss.all, sty.columns___8HOxz)}
                >
                  <div className={classNames(projectcss.all, sty.column__a8AS)}>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__vfTXa)}
                      displayHeight={"230px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/frontend/images/image.jpeg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__hl91)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__wvFll
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nmW4Z
                          )}
                        >
                          {"January 03, 2021"}
                        </div>

                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__joPgr
                          )}
                        >
                          {"Convincing reasons you need to learn"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__k3Ml3
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                          }
                        </div>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__dr7Ef
                          )}
                          color={"softBlue" as const}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__b86RK
                              )}
                              role={"img"}
                            />
                          }
                          shape={"rounded" as const}
                          showEndIcon={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kyyv
                            )}
                          >
                            {"READ MORE"}
                          </div>
                        </Button>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__ge2Zv)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fydkm)}
                      displayHeight={"230px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/frontend/images/image8.jpeg",
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__yrRo0)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.column__lGvO)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qq7BJ
                          )}
                        >
                          {"January 03, 2021"}
                        </div>

                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__zkNr4
                          )}
                        >
                          {"The five devices you need to work anytime"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tV1C
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                          }
                        </div>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__jxi1E
                          )}
                          color={"softBlue" as const}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vCtFs
                              )}
                              role={"img"}
                            />
                          }
                          shape={"rounded" as const}
                          showEndIcon={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hBkTb
                            )}
                          >
                            {"READ MORE"}
                          </div>
                        </Button>
                      </p.Stack>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__hcupv)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tzvpF)}
                      displayHeight={"230px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/frontend/images/image9.jpeg",
                        fullWidth: 390,
                        fullHeight: 290,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns___9YHV)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4Bumi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uGXl
                          )}
                        >
                          {"January 03, 2021"}
                        </div>

                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__baYgj
                          )}
                        >
                          {"Tiktok Illegally collecting data sharing"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wgST
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                          }
                        </div>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__piboM
                          )}
                          color={"softBlue" as const}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__cjbX1
                              )}
                              role={"img"}
                            />
                          }
                          shape={"rounded" as const}
                          showEndIcon={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__i3EyX
                            )}
                          >
                            {"READ MORE"}
                          </div>
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {true ? (
              <section
                className={classNames(projectcss.all, sty.columns__rStx)}
              >
                <div
                  data-plasmic-name={"outer"}
                  data-plasmic-override={overrides.outer}
                  className={classNames(projectcss.all, sty.outer)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__jfCrY)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__prZjE)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2___1YGgY
                        )}
                      >
                        {"To Make Requests For The\nFurther Information"}
                      </h2>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vAZhh
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                        }
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__zw1D)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___6ZSbD
                        )}
                        color={"blue" as const}
                        link={"#" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lmUsj
                          )}
                        >
                          {"Join With Now"}
                        </div>
                      </Button>
                    </div>
                  </div>
                </div>
              </section>
            ) : null}

            <div className={classNames(projectcss.all, sty.freeBox__dqhvr)}>
              <div className={classNames(projectcss.all, sty.columns__s2KM)}>
                <div className={classNames(projectcss.all, sty.column__in88T)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___4V8Qx
                    )}
                  >
                    {"Make your call to action here."}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__alOM
                    )}
                  >
                    {"Lorem ipsum dolor sit amet, consectetur adipiscing elit."}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__e3Asc)}
                    color={"blue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg___1IzBh)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w1L0C
                      )}
                    >
                      {"Start Now"}
                    </div>
                  </Button>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__kp8Ep)}>
              <div
                data-plasmic-name={"footerTop"}
                data-plasmic-override={overrides.footerTop}
                className={classNames(projectcss.all, sty.footerTop)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__tuVZ)}>
                  <div
                    className={classNames(projectcss.all, sty.columns___3BD8J)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__uAjev)}
                    >
                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg__bxf1U)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iDoTe
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                        }
                      </div>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.column__fkMdx)}
                    >
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__ha7
                        )}
                      >
                        {"Menu"}
                      </h5>

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__jdLw
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Privacy Policy"}
                      </p.PlasmicLink>

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__cgFu9
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Terms of Service"}
                      </p.PlasmicLink>

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__eTDiU
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Pricing "}
                      </p.PlasmicLink>

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__b9Ydp
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Contact"}
                      </p.PlasmicLink>

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__gbLYu
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Blog"}
                      </p.PlasmicLink>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__xEgrc)}
                    >
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___5U28D
                        )}
                      >
                        {"Gallery"}
                      </h5>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__yRqgl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__yC9Jp
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__tmMet)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image11.jpeg",
                              fullWidth: 390,
                              fullHeight: 290,
                              aspectRatio: undefined
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__d83Ij
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__vpiaj)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image12.jpeg",
                              fullWidth: 390,
                              fullHeight: 290,
                              aspectRatio: undefined
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__dx5Ni
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__lJBbe)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image9.jpeg",
                              fullWidth: 390,
                              fullHeight: 290,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__fguR
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__nyUpn
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__fJusg)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image11.jpeg",
                              fullWidth: 390,
                              fullHeight: 290,
                              aspectRatio: undefined
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__aSwc1
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__ylKD)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image12.jpeg",
                              fullWidth: 390,
                              fullHeight: 290,
                              aspectRatio: undefined
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__upio2
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__ebDum)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/frontend/images/image9.jpeg",
                              fullWidth: 390,
                              fullHeight: 290,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"footerBottom"}
                data-plasmic-override={overrides.footerBottom}
                className={classNames(projectcss.all, sty.footerBottom)}
              >
                <div
                  data-plasmic-name={"container2"}
                  data-plasmic-override={overrides.container2}
                  className={classNames(projectcss.all, sty.container2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gRRn5
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "© Company Name. All rights reserved. This site proudly built with "
                        }
                      </React.Fragment>
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__t3Px4
                        )}
                        component={Link}
                        href={"https://www.plasmic.app/" as const}
                        platform={"nextjs"}
                      >
                        {"Plasmic"}
                      </p.PlasmicLink>
                      <React.Fragment>{"."}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            </div>
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "h1",
    "features",
    "container4",
    "outerRow2",
    "row2",
    "container5",
    "outerRow3",
    "row4",
    "container6",
    "outerRow4",
    "row3",
    "testimonials",
    "outer",
    "footerTop",
    "footerBottom",
    "container2"
  ],
  h1: ["h1"],
  features: [
    "features",
    "container4",
    "outerRow2",
    "row2",
    "container5",
    "outerRow3",
    "row4",
    "container6",
    "outerRow4",
    "row3"
  ],
  container4: ["container4", "outerRow2", "row2"],
  outerRow2: ["outerRow2", "row2"],
  row2: ["row2"],
  container5: ["container5", "outerRow3", "row4"],
  outerRow3: ["outerRow3", "row4"],
  row4: ["row4"],
  container6: ["container6", "outerRow4", "row3"],
  outerRow4: ["outerRow4", "row3"],
  row3: ["row3"],
  testimonials: ["testimonials"],
  outer: ["outer"],
  footerTop: ["footerTop"],
  footerBottom: ["footerBottom", "container2"],
  container2: ["container2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  h1: "h1";
  features: "section";
  container4: "div";
  outerRow2: "div";
  row2: "div";
  container5: "div";
  outerRow3: "div";
  row4: "div";
  container6: "div";
  outerRow4: "div";
  row3: "div";
  testimonials: "section";
  outer: "div";
  footerTop: "div";
  footerBottom: "div";
  container2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewPage__VariantsArgs;
    args?: PlasmicNewPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNewPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNewPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNewPage__ArgProps,
      internalVariantPropNames: PlasmicNewPage__VariantProps
    });

    return PlasmicNewPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage";
  } else {
    func.displayName = `PlasmicNewPage.${nodeName}`;
  }
  return func;
}

export const PlasmicNewPage = Object.assign(
  // Top-level PlasmicNewPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    features: makeNodeComponent("features"),
    container4: makeNodeComponent("container4"),
    outerRow2: makeNodeComponent("outerRow2"),
    row2: makeNodeComponent("row2"),
    container5: makeNodeComponent("container5"),
    outerRow3: makeNodeComponent("outerRow3"),
    row4: makeNodeComponent("row4"),
    container6: makeNodeComponent("container6"),
    outerRow4: makeNodeComponent("outerRow4"),
    row3: makeNodeComponent("row3"),
    testimonials: makeNodeComponent("testimonials"),
    outer: makeNodeComponent("outer"),
    footerTop: makeNodeComponent("footerTop"),
    footerBottom: makeNodeComponent("footerBottom"),
    container2: makeNodeComponent("container2"),

    // Metadata about props expected for PlasmicNewPage
    internalVariantProps: PlasmicNewPage__VariantProps,
    internalArgProps: PlasmicNewPage__ArgProps
  }
);

export default PlasmicNewPage;
/* prettier-ignore-end */
