// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7iuSa1MtYgfxVkY23CKsNe
// Component: g-GPcOLGQq
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_frontend.module.css"; // plasmic-import: 7iuSa1MtYgfxVkY23CKsNe/projectcss
import sty from "./PlasmicPage3.module.css"; // plasmic-import: g-GPcOLGQq/css

export type PlasmicPage3__VariantMembers = {};

export type PlasmicPage3__VariantsArgs = {};
type VariantPropType = keyof PlasmicPage3__VariantsArgs;
export const PlasmicPage3__VariantProps = new Array<VariantPropType>();

export type PlasmicPage3__ArgsType = {};
type ArgPropType = keyof PlasmicPage3__ArgsType;
export const PlasmicPage3__ArgProps = new Array<ArgPropType>();

export type PlasmicPage3__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultPage3Props {}

export const defaultPage3__Args: Partial<PlasmicPage3__ArgsType> = {};

function PlasmicPage3__RenderFunc(props: {
  variants: PlasmicPage3__VariantsArgs;
  args: PlasmicPage3__ArgsType;
  overrides: PlasmicPage3__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultPage3__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPage3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPage3__VariantsArgs;
    args?: PlasmicPage3__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPage3__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPage3__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPage3__ArgProps,
      internalVariantPropNames: PlasmicPage3__VariantProps
    });

    return PlasmicPage3__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPage3";
  } else {
    func.displayName = `PlasmicPage3.${nodeName}`;
  }
  return func;
}

export const PlasmicPage3 = Object.assign(
  // Top-level PlasmicPage3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPage3
    internalVariantProps: PlasmicPage3__VariantProps,
    internalArgProps: PlasmicPage3__ArgProps
  }
);

export default PlasmicPage3;
/* prettier-ignore-end */
